name: Linter
on: push
permissions:
  contents: write

jobs:
  yamllint:
    name: Yaml doc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: github/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          FIX_PYTHON_BLACK: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_PYLINT: true
          FIX_PYTHON_ISORT: true
          VALIDATE_PYTHON_ISORT: true
