name: First linter runner
on: push

jobs:
  yamllint:
    name: Yaml doc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: superlinter slim
        uses: super-linter/slim@v7.6.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
